import type { Metadata } from "next";
import { Montserrat, Bebas_Neue, Open_Sans } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const monserat = Montserrat({
  subsets: ["latin"],
  variable: "--font-monserat",
  weight: ["300", "400", "500", "600", "700"],
});

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-openSans",
  weight: ["400", "700"],
});

const bebas = Bebas_Neue({
  subsets: ["latin"],
  variable: "--font-bebas",
  weight: "400",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${monserat.variable} ${bebas.variable} ${openSans.variable} font-monserat antialiased`}>
        {children}
      </body>
    </html>
  );
}
