import {
  mudrikCrr1,
  mudrikCrr2,
  mudrikCrr3,
  mudrikCrr7,
  mudrikCrr5,
  mudrikCrr6,
  mudrikCrr8,
  mudrikCrr9,
  mudrikCrr10,
  mudrikCrr11,
  mudrikCrr12,
  mudrikCrr13,
  mudrikCrr14,
  mudrikCrr15,
} from "@/public/images/mudrik-crr";
import {
  mudrikKindegarden1,
  mudrikKindegarden2,
  mudrikKindegarden3,
  mudrikKindegarden4,
  mudrikKindegarden5,
  mudrikKindegarden6,
  mudrikKindegarden7,
  mudrikKindegarden8,
  mudrikKindegarden9,
  mudrikKindegarden10,
  mudrikKindegarden11,
  mudrikKindegarden12,
  mudrikKindegarden13,
  mudrikKindegarden14,
  mudrikKindegarden15,
  mudrikKindegarden16,
} from "@/public/images/mudrik-kindegarden";

import {
  ismart2,
  ismart3,
  ismart4,
  ismart5,
  ismart6,
  ismart7,
  ismart8,
  ismart9,
  ismart10,
} from "@/public/images/ismart";
import {
  kvitka1,
  kvitka2,
  kvitka3,
  kvitka4,
  kvitka5,
  kvitka6,
  kvitka7,
  kvitka8,
  kvitka9,
  kvitka10,
  kvitka11,
  kvitka12,
  kvitka13,
  kvitka14,
  kvitka15,
  kvitka16,
  kvitka17,
  kvitka18,
  kvitka19,
  kvitka20,
} from "@/public/images/kvitka";
import {
  maliata1,
  maliata2,
  maliata3,
  maliata4,
  maliata5,
  maliata6,
  maliata7,
  maliata8,
  maliata9,
  maliata10,
  maliata11,
  maliata12,
  maliata13,
  maliata14,
  maliata15,
  maliata16,
  maliata17,
  maliata18,
  maliata19,
  maliata20,
  maliata21,
  maliata22,
  maliata23,
  maliata24,
  maliata25,
  maliata26,
  maliata27,
  maliata28,
  maliata29,
  maliata30,
  maliata31,
  maliata32,
} from "@/public/images/maliata";
import {
  mudrikSchool1,
  mudrikSchool2,
  mudrikSchool3,
  mudrikSchool4,
  mudrikSchool5,
  mudrikSchool6,
  mudrikSchool7,
  mudrikSchool8,
  mudrikSchool9,
  mudrikSchool10,
  mudrikSchool11,
  mudrikSchool12,
  mudrikSchool13,
  mudrikSchool14,
  mudrikSchool15,
  mudrikSchool16,
  mudrikSchool17,
  mudrikSchool19,
  mudrikSchool20,
  mudrikSchool21,
  mudrikSchool22,
  mudrikSchool23,
} from "@/public/images/mudrik-school";
import {
  ucook1,
  ucook3,
  ucook5,
  ucook6,
  ucook7,
  ucook8,
  ucook9,
  ucook10,
  ucook11,
  ucook12,
  ucook13,
  ucook14,
  ucook15,
} from "@/public/images/ucook";
import {
  solodki1,
  solodki2,
  solodki3,
  solodki4,
  solodki5,
  solodki6,
  solodki7,
  solodki8,
  solodki9,
  solodki10,
  solodki11,
  solodki12,
  solodki13,
  solodki14,
} from "@/public/images/solodki/solodki";

export const FRANCHISE_LIST = [
  {
    id: "0933383786",
    title: "ЦЕНТР РАННЬОГО РОЗВИТКУ",
    description:
      "Центр раннього розвитку, який випереджає час! Ексклюзивна модель без аналогів — створюйте майбутнє з нами.",
    imageSrcList: [
      mudrikCrr1,
      mudrikCrr2,
      mudrikCrr3,
      mudrikCrr7,
      mudrikCrr5,
      mudrikCrr6,
      mudrikCrr8,
      mudrikCrr9,
      mudrikCrr10,
      mudrikCrr11,
      mudrikCrr12,
      mudrikCrr13,
      mudrikCrr14,
      mudrikCrr15,
    ],
    promo: "Центр раннього розвитку “Мудрик” за ціною:",
    prices: [
      { id: "5084756453", deprecatedPrice: "10 000", actualPrice: "6 600", type: undefined },
    ],
  },
  {
    id: "6540624003",
    title: "САДОЧОК ПОВНОГО ДНЯ",
    description:
      "Створіть своє щасливе місце з “Мудриком”! Унікальна франшиза, де навчання, гра та розвиток ідуть рука об руку!”",
    imageSrcList: [
      mudrikKindegarden1,
      mudrikKindegarden2,
      mudrikKindegarden3,
      mudrikKindegarden4,
      mudrikKindegarden5,
      mudrikKindegarden6,
      mudrikKindegarden7,
      mudrikKindegarden8,
      mudrikKindegarden9,
      mudrikKindegarden10,
      mudrikKindegarden11,
      mudrikKindegarden12,
      mudrikKindegarden13,
      mudrikKindegarden14,
      mudrikKindegarden15,
      mudrikKindegarden16,
    ],
    promo: "Садок повного дня “Мудрик” за ціною:",
    prices: [
      { id: "6115274160", deprecatedPrice: "10 000", actualPrice: "7 700", type: undefined },
    ],
  },
  {
    id: "5391955418",
    title: "Приватна ШКОЛА",
    description: "Створіть простір, де діти зростають щасливими й готовими до майбутніх успіхів.",
    imageSrcList: [
      mudrikSchool1,
      mudrikSchool2,
      mudrikSchool3,
      mudrikSchool4,
      mudrikSchool5,
      mudrikSchool6,
      mudrikSchool7,
      mudrikSchool8,
      mudrikSchool9,
      mudrikSchool10,
      mudrikSchool11,
      mudrikSchool12,
      mudrikSchool13,
      mudrikSchool14,
      mudrikSchool15,
      mudrikSchool16,
      mudrikSchool17,
      mudrikSchool19,
      mudrikSchool20,
      mudrikSchool21,
      mudrikSchool22,
      mudrikSchool23,
    ],
    promo: "Приватна школа “Мудрик” за ціною:",
    prices: [
      { id: "7885097379", deprecatedPrice: "15 000", actualPrice: "8 800", type: undefined },
    ],
  },
  {
    id: "0838006502",
    title: "ЦЕНТР РАННЬОГО РОЗВИТКУ i”m smart",
    description:
      "Будьте першим, хто відкриє “I’m Smart” у Європі — центр раннього розвитку, що готує дітей до успіху!",
    imageSrcList: [
      ismart2,
      ismart3,
      ismart4,
      ismart5,
      ismart6,
      ismart7,
      ismart8,
      ismart9,
      ismart10,
    ],
    promo: "Центр раннього розвитку “I’m SMART” за ціною:",
    prices: [
      { id: "1037369833", deprecatedPrice: "12 000", actualPrice: "7 700", type: undefined },
    ],
  },
  {
    id: "9971969815",
    title: "Студія кулінарних вражень U.COOK",
    description:
      "Відкрийте студію кулінарних вражень і подаруйте людям унікальні гастрономічні емоції! Масштабуйте успіх із бізнесом, що поєднує кулінарію, творчість і незабутні враження.",
    imageSrcList: [
      ucook1,
      ucook3,
      ucook5,
      ucook6,
      ucook7,
      ucook8,
      ucook9,
      ucook10,
      ucook11,
      ucook12,
      ucook13,
      ucook14,
      ucook15,
    ],
    promo: "Студія кулінарних вражень “UCOOK” за ціною:",
    prices: [{ id: "2983285713", deprecatedPrice: "9 900", actualPrice: "6 600", type: undefined }],
  },
  {
    id: "7900022351",
    title: "CТУДІЯ КВІТКОВОГО БУТИКУ",
    description:
      "Запустіть унікальну франшизу квіткового бутіка, що захоплює з першого погляду! Створюйте простір, де краса стає мистецтвом і бізнесом одночасно.",
    imageSrcList: [
      kvitka1,
      kvitka2,
      kvitka3,
      kvitka4,
      kvitka5,
      kvitka6,
      kvitka7,
      kvitka8,
      kvitka9,
      kvitka10,
      kvitka11,
      kvitka12,
      kvitka13,
      kvitka14,
      kvitka15,
      kvitka16,
      kvitka17,
      kvitka18,
      kvitka19,
      kvitka20,
    ],
    promo: "Студія квіткового бутику “Kvitka.Bar” за ціною:",
    prices: [{ id: "4379285018", deprecatedPrice: "7 900", actualPrice: "5 500", type: undefined }],
  },
  {
    id: "3725688619",
    title: "ДИТЯЧИЙ ЦЕНТР РОЗВАГ",
    description:
      "Відкрийте дитячий центр розваг “Малята на Тата” — місце, де кожен момент наповнений радістю та натхненням! Створіть світ безмежних можливостей для дітей і успішний бізнес для себе.",
    imageSrcList: [
      maliata1,
      maliata2,
      maliata3,
      maliata4,
      maliata5,
      maliata6,
      maliata7,
      maliata8,
      maliata9,
      maliata10,
      maliata11,
      maliata12,
      maliata13,
      maliata14,
      maliata15,
      maliata16,
      maliata17,
      maliata18,
      maliata19,
      maliata20,
      maliata21,
      maliata22,
      maliata23,
      maliata24,
      maliata25,
      maliata26,
      maliata27,
      maliata28,
      maliata29,
      maliata30,
      maliata31,
      maliata32,
    ],
    promo: "Дитячий розважальний центр “Малята на Тата” за ціною:",
    prices: [
      { id: "9224389740", deprecatedPrice: "5 900", actualPrice: "4 900", type: "s" },
      { id: "7745392340", deprecatedPrice: "7 900", actualPrice: "5 900", type: "m" },
      { id: "4406708403", deprecatedPrice: "9 900", actualPrice: "6 900", type: "l" },
    ],
  },
  {
    id: "5024139006",
    title: "Кавʼярня - кондитерська",
    description:
      "Запустіть кондитерську кав’ярню, де кожен десерт — це шедевр! Створюйте смачний бізнес, який приносить радість і задоволення кожному гостю.",
    imageSrcList: [
      solodki1,
      solodki2,
      solodki3,
      solodki4,
      solodki5,
      solodki6,
      solodki7,
      solodki8,
      solodki9,
      solodki10,
      solodki11,
      solodki12,
      solodki13,
      solodki14,
    ],
    promo: "Кавʼярня - кондитерська “Солодкі історії” за ціною:",
    prices: [
      { id: "8178831171", deprecatedPrice: "7 900", actualPrice: "4 900", type: "s" },
      { id: "5955469388", deprecatedPrice: "8 900", actualPrice: "5 900", type: "m" },
      { id: "8367536001", deprecatedPrice: "11 900", actualPrice: "6 900", type: "l" },
    ],
  },
];
